sudo: false
language: ruby

matrix:
  include:
    - rvm: 2.3
    - rvm: 2.4
    - rvm: 2.5
    - rvm: 2.6
    - rvm: ruby-head
    - rvm: jruby
    - rvm: truffleruby
  allow_failures:
    - rvm: ruby-head
